version: 2
jobs:
  build:
    working_directory: ~/code
    
    docker:
      - image: circleci/android:api-25-alpha

    environment:
      JVM_OPTS: -Xmx3200m
      ANDROID_HOME: /usr/local/android-sdk-linux
      ADB_INSTALL_TIMEOUT: 240

    steps:
      - checkout
        - run:
            name: Download Dependencies
            command: chmod +x gradlew

        - run:
            name: Download Dependencies
            command: sudo ./gradlew dependencies
                 
