Version: 2
jobs:
  builds:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    #general:
          #artifacts:
              #- /home/jaser/AndroidStudioProjects/AndroidDemoTestProject/app/build/outputs
    environment:
      ANDROID_HOME: /usr/local/android-sdk-linux
      ADB_INSTALL_TIMEOUT: 240
    
    steps:
      - run: sudo chmod +x gradlew
      - run: echo y | android update sdk --no-ui --all --filter "tools,android-26,build-tools-27.0.3,platform-tools,extra-android-m2repository,extra-android-support,extra-google-m2repository,extra-google-google_play_services"
      - run: sudo echo yes | android update sdk --no-ui --all
      - run: sudo ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies

      - run: emulator -avd circleci-android22 -no-window:
          background: true
          parallel: true

      - run: circle-android wait-for-boot
           # unlock emulator
      - run: sleep 30
      - run: adb shell input keyevent 82
      - run: - ./gradlew assemble connectedDebugAndroidTest -PdisablePreDex --console=plain --info
